apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: petclinic-gateway-cert
  namespace: default
spec:
  dnsNames:
  - petclinic.eks-use1.tanzu.pro
  secretName: petclinic-gateway-tls-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
